import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import path from "node:path";

const production = process.argv[2] === "production";
const projectRoot = process.cwd();

const context = await esbuild.context({
  absWorkingDir: projectRoot,
  banner: {
    js: `/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\nSource: local Obsidian plugin dragdrop\n*/`,
  },
  entryPoints: [path.join(projectRoot, "main.ts")],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: path.join(projectRoot, "main.js"),
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
